### PR TITLE
Lab09

### PR DESCRIPTION
**Pull request by qwertyuiop5040**
Updated README.md, also added issues.

#24 #25 #26 #27 #28

### CODE REVIEW

**Comment by qwertyuiop5040** [comment]
We aren't finished: will edit when finished

**Comment by Tektonbuilds** [comment]
You should probably make your remarks a bit longer

**Comment by AlexanderJBauer** [comment]
F16_lab09.md now included

**Comment by qwertyuiop5040** [comment]
I'm not too sure which file you are referring to in your comment @Tektonbuilds. I looked over the F16_lab09.md, issues look self explanatory enough.

**Pull request merged**
